### PR TITLE
Adding Graphite Handler vars to diamond.conf

### PR DESCRIPTION
**Pull request by tavislikedavis**
### Reviewers

- [x]  @jwitko 

cc: 
### High level summary
Adding Graphite Handler vars to diamond.conf

### CODE REVIEW

**Comment by tavislikedavis** [comment]
This test is expected to fail most details on why in PR 13.

**Comment by jwitko** [comment]
Can you explain a little more about this PR?   Why are we adding these handlers?  (Did they exist in the previous role but don't here?  What do they do?  When are they used?)

**Comment by tavislikedavis** [comment]
They exist in the previous role and are used.

**Comment by jwitko** [comment]
:ship:

**Pull request merged**
